version: '3'
services:
  web:
    build:
        dockerfile: Dockerfile 
        context: .
    depends_on:      
      - redis-server

    network_mode: host
    environment:
      NODE_ENV: development
      DB_HOST: 172.22.18.120
      DB_PASSWORD: PonnusKannan@2
      DB_USER: postgres
      DB_DATABASE: foctalk
      DB_PORT: 5433
      DB_SYNC: true
  redis-server:
    image: redis:latest
    ports:
      - '6379:6379'

 
